apiVersion: batch/v1
kind: Job
metadata:
  name: es-init-index
spec:
  template:
    spec:
      containers:
      - name: init-index
        image: vluciani/node-search-app:python-indexation-1.3
        command: ["/bin/sh", "-c", "./elastic_setup_sh/build_settings.sh"]
        env:
        - name: ELASTIC_USER
          value: "elastic" 
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-secret 
              key: password
      restartPolicy: Never
