apiVersion: batch/v1
kind: Job
metadata:
  name: es-init-index
spec:
  template:
    spec:
      containers:
      - name: init-index
        image: vluciani/node-search-app:python-indexation-1.11
        command: ["python", "elastic_setup/build_settings.py"]
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        - name: ELASTIC_USER
          value: "elastic" 
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-secret 
              key: password
      restartPolicy: Never
